apiVersion: apps/v1
kind: Deployment
metadata:
  name: soat3-ms-pagamentos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: soat3-ms-pagamentos
  template:
    metadata:
      labels:
        app: soat3-ms-pagamentos
    spec:
      containers:
        - name: soat3-ms-pagamentos
          image: franciscosviana/soat3-ms-pagamentos:v1
          ports:
            - containerPort: 8082
          env:
            - name: MP_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: pagamentos-config-secret
                  key: mp_access_token
---
apiVersion: v1
kind: Service
metadata:
  name: soat3-ms-pagamentos
spec:
  type: NodePort
  selector:
    app: soat3-ms-pagamentos
  ports:
    - protocol: TCP
      port: 8082
      nodePort: 32003
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pagamentos-config-secret
stringData:
  mp_access_token: "TEST-8555804592568661-101216-ab681ffa7e53364dc510aecee2a4ae6e-99090660"
